name: v2 CI
on: [push]
defaults:
 run:
  working-directory: ./v2
jobs:
  test:
    name: Test v2 on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Bun 1.1.2
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
              
      - name: Install Dependencies
        run: bun install

      - name: Test (uses node internally)
        run: bun run test
  lint:
    name: Lint v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Bun 1.1.2
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.2

      - name: Install Dependencies
        run: bun install

      - name: Lint
        run: bun run lint